BUDRATE: 115200
EHOST: ''
FILE_SIZE_LIMIT: 10000000
HOST: gAAAAABfxTrP6q5YvIND-1bJKX3GQy-18nbUQPxWCHSMUdcDoo8dkQfWjYUVfB1YdayuwselF5HZ4m7C4eTlz_EFE15Jad7zx9wuAOpnY1THcAbMJbzCBL2oHvG-DN7ZaKoTaLrT5-bdgqRKl_Tq64kvtdvg8ricIA==
LOCAL_DATA_FILE: /16070816479044795-data.csv
LOCAL_DATA_PATH: ryAowKokzxFxbrVSctUGNUzxlKrjETFCtZaifnglEOU=
LOCAL_DATA_ROOT: C:/Users/Owner/Desktop/PowMon/DataCollector/Data
LOG_LEVEL: 1
OFFSET: 0
POLLING_DELAY: 0.5
PROJECT_ROOT: C:/Users/Owner/Desktop/PowMon/DataCollector
REMOTE_SAVE: false
SENSORS:
- PORT: COM4
  SENSORS_ID: VIC
- PORT: COM14
  SENSORS_ID: ATT
SNS: 0.066
SYNC_WRITE: false
TIMEOUT: 0.1
VPP: 0.00488
VCC : 5
