BUDRATE: 115200
FILE_SIZE_LIMIT: 1000000
HOST: gAAAAABfxTrP6q5YvIND-1bJKX3GQy-18nbUQPxWCHSMUdcDoo8dkQfWjYUVfB1YdayuwselF5HZ4m7C4eTlz_EFE15Jad7zx9wuAOpnY1THcAbMJbzCBL2oHvG-DN7ZaKoTaLrT5-bdgqRKl_Tq64kvtdvg8ricIA==
LOCAL_DATA_FILE: /00000000000000000-data.csv
LOCAL_DATA_PATH: ryAowKokzxFxbrVSctUGNUzxlKrjETFCtZaifnglEOU=
LOCAL_DATA_ROOT: C:/Users/Owner/Desktop/PowMon/DataCollector/Data
PROJECT_ROOT: C:/Users/Owner/Desktop/PowMon/DataCollector
OFFSET: 2.5
SENSORS:
- PORT: COM14
  SENSORS_ID: CRS02
SENSORS_CNT: 2
SNS: 0.066
TIMEOUT: 0.1
VPP: 0.00488
LOG_LEVEL: 3
SYNC_WRITE: False